server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    # API — proxy do gatewaya (same-origin, bez CORS)
    location /api/ {
        proxy_pass http://gateway:8080;
    }

    # SPA — wszystkie ścieżki serwuj z index.html (routing Angulara)
    location / {
        try_files $uri $uri/ /index.html;
    }
}
