spring.application.name=Gateway
server.port=8080
eureka.client.enabled=false
spring.cloud.config.enabled=false
spring.cloud.gateway.httpclient.connect-timeout=10000
spring.cloud.gateway.httpclient.response-timeout=5m