spring.application.name=CompanyService
spring.datasource.url=jdbc:postgresql://localhost:5432/stocks
spring.datasource.username=postgres
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update
eureka.client.enabled=false
server.port=8081